### ISSUE TITLE
OpenLLM 0.5.X requires vllm >=0.4.2 , vllm is not available on conda-forge

### ISSUE THREAD

**Issue by rxm7706** [conda-forge/openllm-feedstock#9]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

cc @jakirkham @h-vetinari @jan-janssen @RaulPPelaez

**TODO**
* [ ] openllm 0.5.X requires vllm >=0.4.2 , not available on conda-forge, needs new feedstock.
* [x] vllm >=0.4.2 requires prometheus-fastapi-instrumentator >=7.0.0 , needs feedstock update.
       -  https://github.com/conda-forge/prometheus-fastapi-instrumentator-feedstock/pull/7
* [x] vllm >=0.4.2 requires vllm-nccl-cu12 >=2.18,<2.19, needs new feedstock.
       - https://github.com/conda-forge/staged-recipes/pull/26495
* [x] vllm >=0.4.2 requires lm-format-enforcer ==0.9.8, needs new feedstock.
       - https://github.com/conda-forge/staged-recipes/pull/26494
* [X] vllm >=0.4.2 requires xformers ==0.0.26.post1 , needs feedstock update.
       - https://github.com/conda-forge/xformers-feedstock/pull/15
       - https://github.com/conda-forge/xformers-feedstock/pull/24
### Installed packages

```shell
feedstock
```

### Environment info

```shell
feedstock
```

**Comment by jakirkham** [comment]
Could you please raise new package requests on `staged-recipes`?

**Comment by h-vetinari** [comment]
> Could you please raise new package requests on `staged-recipes`?

There's a PR: https://github.com/conda-forge/staged-recipes/pull/26595
